---
title: "GLM in R"
author: "Kailas Venkat"
date: "March 14, 2017"
output: html_document
toc: true
toc_float: true
theme: united 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

## Load dataset

The Data.

```{r data}
library(haven); library(tidyverse); library(ggthemes)
productivity <- read_dta("C:/Users/kvenkita/Dropbox (UNC Charlotte)/R Bootcamp/Data/productivity.dta")
```
\addcontentsline{toc}{section}{Abstract}

## Including Plots

```{r gsp, echo=TRUE}

scatter<-ggplot(productivity,aes(gsp,public))+geom_jitter()+theme_few()
print(scatter)
```
## Plots2
```{r private}
scatter1<-ggplot(productivity,aes(gsp,private))+geom_jitter()+geom_smooth()+theme_few()
print(scatter1)
```
## Including Plots3
```{r private by state}
scatter2<-ggplot(productivity,aes(gsp,private))+geom_jitter()+geom_smooth()+facet_wrap(~state,ncol=9)+theme_few()
print(scatter2)
```
```{r private density}
scatter1<-ggplot(productivity,aes(gsp,private))+geom_jitter()+geom_smooth()+geom_density2d()+theme_few()
print(scatter1)
```
##summary of unemp, public etc
```{r}
sum.st <- subset(productivity, select = c("unemp", "public", "private", "gsp"))
summary(sum.st)
```
##correlations
```{r}
cor(sum.st)
```

##Fit regression
```{r}
prod.mod <- lm(gsp ~ public, # regression formula
              data=productivity) # data set
# Summarize and print the results
summary(prod.mod) # show regression coefficients table
#summary(lm(gsp ~ public + unemp, data = productivity))

class(prod.mod)
names(prod.mod)
methods(class = class(prod.mod))[1:9]

confint(prod.mod)
deviance(prod.mod)
hist(residuals(prod.mod))

par(mar = c(4, 4, 2, 2), mfrow = c(1, 2)) #optional
plot(prod.mod, which = c(1, 2)) # "which" argument optional


# fit another model, adding house and senate as predictors
prod.private.mod <-  lm(gsp ~ public + unemp + private,
                      data = na.omit(productivity))
prod.mod <- update(prod.mod, data=na.omit(productivity))
# compare using the anova() function
anova(prod.mod, prod.private.mod)
coef(summary(prod.private.mod))



#Show the results
#coef(summary(prod.expense.by.percent)) # show regression coefficients table

library(lme4)

gsp.mod <-lmer(gsp ~ 1 + (1|region),
             data=productivity, REML = FALSE)
summary(gsp.mod)

gsp.mod2 <-lmer(gsp~public + (1|region),
             data=productivity,
             REML = FALSE) 
summary(gsp.mod2)


anova(gsp.mod, gsp.mod2)

```
## 5.6 Random slopes
## ─────────────────



gsp.mod3 <- lmer(gsp~unemp + (unemp|region), data=productivity,
               REML = FALSE) 
summary(gsp.mod3)

##Fit regression
```
#install.packages("multilevel")
library(multilevel)
data(bh1996, package="multilevel")
describe(bh1996)
